server:
  port: 8082
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pos_db
    username: andrewramirez
    password: sul4m1995*
  jpa:
    properties:
      hibernate.format_sql: true
  application:
    name: ms-products-and-categories